const data = {
  lessorAcceptanceRate: {
    weekly: [
      {
        data: [
          [Date.UTC(1970, 0, 1), 2],
          [Date.UTC(1970, 0, 7), 55],
          [Date.UTC(1970, 0, 14), 70],
          [Date.UTC(1970, 0, 21), 14],
          [Date.UTC(1970, 1, 1), 150],
          [Date.UTC(1970, 1, 7), 69],
          [Date.UTC(1970, 1, 14), 200],
          [Date.UTC(1970, 1, 21), 220],
          [Date.UTC(1970, 2, 1), 120],
          [Date.UTC(1970, 2, 7), 49],
        ],
      },
    ],
    monthly: [
      {
        data: [
          [Date.UTC(1970, 0, 1), 2],
          [Date.UTC(1970, 0, 2), 55],
          [Date.UTC(1970, 0, 3), 70],
          [Date.UTC(1970, 0, 4), 14],
          [Date.UTC(1970, 0, 5), 150],
          [Date.UTC(1970, 0, 6), 69],
          [Date.UTC(1970, 0, 7), 200],
          [Date.UTC(1970, 0, 9), 220],
          [Date.UTC(1970, 0, 20), 120],
          [Date.UTC(1970, 0, 27), 49],
        ],
      },
    ],
    sixMonths: [
      {
        data: [
          [Date.UTC(1970, 0, 1), 0],
          [Date.UTC(1970, 1, 1), 14],
          [Date.UTC(1970, 2, 1), 4],
          [Date.UTC(1970, 3, 1), 20],
          [Date.UTC(1970, 4, 1), 4],
          [Date.UTC(1970, 5, 1), 1],
        ],
      },
    ],
    yearly: [
      {
        data: [
          [Date.UTC(1970, 0, 1), 0],
          [Date.UTC(1970, 1, 1), 14],
          [Date.UTC(1970, 2, 1), 4],
          [Date.UTC(1970, 3, 1), 20],
          [Date.UTC(1970, 4, 1), 4],
          [Date.UTC(1970, 5, 1), 1],
          [Date.UTC(1970, 6, 1), 6],
          [Date.UTC(1970, 7, 1), 10],
          [Date.UTC(1970, 8, 1), 5],
          [Date.UTC(1970, 9, 1), 16],
          [Date.UTC(1970, 10, 1), 1],
          [Date.UTC(1970, 11, 1), 4],
        ],
      },
    ],
  },
  homeRequestsEn: [
    {
      "Requset ID": 1,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "Requset ID": 2,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "Requset ID": 3,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "Requset ID": 4,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
  ],
  homeRequestsAr: [
    {
      "رقم المعاملة": 1,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "رقم المعاملة": 2,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "رقم المعاملة": 3,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "رقم المعاملة": 4,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
  ],
  ServiceStatusesEn: [
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
  ],
  ServiceStatusesAr: [
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
  ],
  servicesList: [
    {
      titleEn: "Contract Details",
      titleAr: "تفاصيل العقد",
      link: "contractDetails",
    },
    {
      titleEn: "Transfer of Rights",
      titleAr: "نقل الحقوق",
      link: "TransferOfRights",
    },
    {
      titleEn: "Contract Details",
      titleAr: "الخدمة بالعربية",
      link: "contractDetails",
    },
    {
      titleEn: "Repossession Request",
      titleAr: "الخدمة بالعربية",
      link: "RepossessionRequest",
    },
    {
      titleEn: "Contract Details",
      titleAr: "الخدمة بالعربية",
      link: "contractDetails",
    },
    {
      titleEn: "Repossession Request",
      titleAr: "الخدمة بالعربية",
      link: "RepossessionRequest",
    },
  ],
  UsersListEn: [
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
  ],
  UsersListAr: [
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
  ],
  InvoicesEn: [
    {
      name: "name 1",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "name 2",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "name 3",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "name 4",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "name 5",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
  ],
  InvoicesAr: [
    {
      name: "إسم 1",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "إسم 2",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "إسم 3",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "إسم 4",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "إسم 5",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
  ],
};
module.exports = data;
