const data = {
  lessorAcceptanceRate: {
    weekly: [
      {
        data: [
          [Date.UTC(1970, 0, 1), 2],
          [Date.UTC(1970, 0, 7), 55],
          [Date.UTC(1970, 0, 14), 70],
          [Date.UTC(1970, 0, 21), 14],
          [Date.UTC(1970, 1, 1), 150],
          [Date.UTC(1970, 1, 7), 69],
          [Date.UTC(1970, 1, 14), 200],
          [Date.UTC(1970, 1, 21), 220],
          [Date.UTC(1970, 2, 1), 120],
          [Date.UTC(1970, 2, 7), 49],
        ],
      },
    ],
    monthly: [
      {
        data: [
          [Date.UTC(1970, 0, 1), 2],
          [Date.UTC(1970, 0, 2), 55],
          [Date.UTC(1970, 0, 3), 70],
          [Date.UTC(1970, 0, 4), 14],
          [Date.UTC(1970, 0, 5), 150],
          [Date.UTC(1970, 0, 6), 69],
          [Date.UTC(1970, 0, 7), 200],
          [Date.UTC(1970, 0, 9), 220],
          [Date.UTC(1970, 0, 20), 120],
          [Date.UTC(1970, 0, 27), 49],
        ],
      },
    ],
    sixMonths: [
      {
        data: [
          [Date.UTC(1970, 0, 1), 0],
          [Date.UTC(1970, 1, 1), 14],
          [Date.UTC(1970, 2, 1), 4],
          [Date.UTC(1970, 3, 1), 20],
          [Date.UTC(1970, 4, 1), 4],
          [Date.UTC(1970, 5, 1), 1],
        ],
      },
    ],
    yearly: [
      {
        data: [
          [Date.UTC(1970, 0, 1), 0],
          [Date.UTC(1970, 1, 1), 14],
          [Date.UTC(1970, 2, 1), 4],
          [Date.UTC(1970, 3, 1), 20],
          [Date.UTC(1970, 4, 1), 4],
          [Date.UTC(1970, 5, 1), 1],
          [Date.UTC(1970, 6, 1), 6],
          [Date.UTC(1970, 7, 1), 10],
          [Date.UTC(1970, 8, 1), 5],
          [Date.UTC(1970, 9, 1), 16],
          [Date.UTC(1970, 10, 1), 1],
          [Date.UTC(1970, 11, 1), 4],
        ],
      },
    ],
  },
  homeRequestsEn: [
    {
      "Requset ID": 1,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "Requset ID": 2,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "Requset ID": 3,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "Requset ID": 4,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
  ],
  homeRequestsAr: [
    {
      "رقم المعاملة": 1,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "رقم المعاملة": 2,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "رقم المعاملة": 3,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
    {
      "رقم المعاملة": 4,
      "Requset Date": "13 Jan 2021 at 12:00 am",
      "Requset Type": "request type",
      CRN: "CRN",
      ARN: "ARN",
      "Contract Open Date": "13 Jan 2002 at 12:00 pm",
      "Approval Date": "13 Jan 2002 at 12:00 pm",
      Status: "status",
    },
  ],
  ServiceStatusesEn: [
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "contract registration",
      completed: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
  ],
  ServiceStatusesAr: [
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
    {
      service: "تسجيل عقد",
      انتهت: 12,
      delayed: 22,
      canceled: 10,
      rejected: 99,
    },
  ],
  servicesList: [
    {
      titleEn: "Contract Registration",
      titleAr: "تفاصيل العقد",
      link: "contractDetails",
      iconUrl: "serviece icons/service-icon1.jpg",
    },

    {
      titleEn: "Payment Update",
      titleAr: "تحديث الدفع",
      link: "paymentUpdate",
      iconUrl: "serviece icons/payment.png",
    },
    {
      titleEn: "Repossession Certificate",
      titleAr: "شهادة التملك",
      link: "RepossessionCertificate",
      iconUrl: "serviece icons/repossision.png",
    },
    {
      titleEn: "Transfer of Rights",
      titleAr: "نقل الحقوق",
      link: "TransferOfRights",
      iconUrl: "serviece icons/transfer-of-rights.png",
    },
    {
      titleEn: "General Enquiry",
      titleAr: "استفسار عام",
      link: "generalEnquiry",
      iconUrl: "serviece icons/general-enquiry.png",
    },
    {
      titleEn: "Contract Closure",
      titleAr: "إقفال العقد",
      link: "contractClosure",
      iconUrl: "serviece icons/contract-closure.png",
    },
    {
      titleEn: "Contract Amendment",
      titleAr: "تعديل العقد",
      link: "contractAmendment",
      iconUrl: "serviece icons/contract-amendment.png",
    },
    {
      titleEn: "Enforcement Certificate",
      titleAr: "شهادة الإنفاذ",
      link: "enforcementCertificate",
      iconUrl: "serviece icons/repossision.png",
    },
  ],
  UsersListEn: [
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "ahmed magdy hassan",
      role: "Manager",
      privileges: ["Chart and Diagrams", "Analytics", "Analytical reports"],
    },
  ],
  UsersListAr: [
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
    {
      userName: "ahmedmagdy",
      fullName: "أحمد مجدى حسن",
      role: "مدير",
      privileges: ["بيانات إحصائية", "احصائيات", "تقارير إحصائية"],
    },
  ],
  InvoicesEn: [
    {
      name: "name 1",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "name 2",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "name 3",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "name 4",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "name 5",
      date: "38 Jan 2021 at 12:00 am",
      type: "type",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
  ],
  InvoicesAr: [
    {
      name: "إسم 1",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "إسم 2",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "إسم 3",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "إسم 4",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
    {
      name: "إسم 5",
      date: "23 يناير 2020 12:0 ص",
      type: "نوع",
      download: [
        { type: "pdf", url: "url" },
        { type: "excel", url: "url" },
      ],
    },
  ],
  ContractDetailsEn: {
    contractNumber: "SIJIL_1Action_asd32",
    creaditInstrumentExpiryDate: "01/12/2020",
    totalLeasingAmount: "2000",
    creaditInstrumentIssueOpenedDate: "SIJIL_1Action_asd32",
    salaryAssignmentFlag: "01/12/2020",
    downPayment: "2000",
    paymentFrequency: "SIJIL_1Action_asd32",
    rightOfWithdrawalCode: "01/12/2020",
    baloonBayment: "2000",
    productStaus: "SIJIL_1Action_asd32",
    terminationProcedureCode: "01/12/2020",
    numberOfInstallments: "2000",
    securityType: "SIJIL_1Action_asd32",
    amountOfUnpaidInstallments: "01/12/2020",
    dispensedAmount: "2000",
  },
  ContractDetailsAr: {
    contractNumber: "SIJIL_1Action_asd32",
    creaditInstrumentExpiryDate: "01/12/2020",
    totalLeasingAmount: "2000",
    creaditInstrumentIssueOpenedDate: "SIJIL_1Action_asd32",
    salaryAssignmentFlag: "01/12/2020",
    downPayment: "2000",
    paymentFrequency: "SIJIL_1Action_asd32",
    rightOfWithdrawalCode: "01/12/2020",
    baloonBayment: "2000",
    productStaus: "SIJIL_1Action_asd32",
    terminationProcedureCode: "01/12/2020",
    numberOfInstallments: "2000",
    securityType: "SIJIL_1Action_asd32",
    amountOfUnpaidInstallments: "01/12/2020",
    dispensedAmount: "2000",
  },
};
module.exports = data;
